###

POST http://localhost:8080/stellenangebote
Content-Type: application/json

{
  "jobTitle": "Marketing Manager (m/w/d)",
  "company": "Marketing Boost GmbH",
  "location": "München, Deutschland",
  "description": "Wir suchen einen Marketing Manager mit nachgewiesener Erfahrung im Aufbau von Marken und der Entwicklung erfolgreicher Marketingstrategien. Kommunikationsgeschick und Kreativität sind gefragt!",
  "deadline": "01.06.2023",
  "startDate": "20.04.2023"
}